name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ewz:
    name: Symfony ${{ matrix.symfony }} (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1, 8.2]
        symfony: [4.4, 5.4, 6.0]
        exclude:
          - php: 8.0
            symfony: 3.4
          - php: 7.2
            symfony: 6.0
          - php: 7.3
            symfony: 6.0
          - php: 7.4
            symfony: 6.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: |
          composer require "symfony/form:^${{ matrix.symfony }}" --no-update
          composer require "symfony/framework-bundle:^${{ matrix.symfony }}" --no-update
          composer require "symfony/security-bundle:^${{ matrix.symfony }}" --no-update
          composer require "symfony/validator:^${{ matrix.symfony }}" --no-update

      - name: Install dependencies PHP
        run: |
          composer install

      - name: Run tests
        run: vendor/bin/phpunit
